const filterListInitial = {
  Grade: {
    JK: false,
    SK: false,
    1: false,
    2: false,
    3: false,
    4: false,
    5: false,
    6: false,
    7: false,
    8: false,
    9: false,
    10: false,
    11: false,
    12: false,
    ESL: false,
    "Spec. Ed.": false,
  },
  Subject: {
    "Physical Education": false,
    "The Arts": false,
    Language: false,
    Mathematics: false,
    "Science and Technology": false,
    "Social Studies": false,
    History: false,
    Geography: false,
    "Canadian and World Studies": false,
    "First Nations, Métis, and Inuit Studies": false,
  },
  Focus: {
    Wellness: false,
    "Climate Change": false,
    "Environmental Justice": false,
    "Indigenous Knowledges": false,
    "Anti-Black Racism": false,
    "Environmental Racism": false,
  },
  Type: {
    Activities: false,
    "Lesson plans": false,
    "Web Link": false,
    Videos: false,
    "Virtual Field Trips": false,
  },
  Use: { Class: false, "Professional Development": false },
  Location: {
    Inside: false,
    Classroom: false,
    Schoolyard: false,
    "Local green space": false,
    "Neighbourhood walk": false,
    Garden: false,
    "At a window": false,
    Balcony: false,
  },
  Duration: {
    "Less than 5 minutes": false,
    "Less than 15 minutes": false,
    "Less than 30 minutes": false,
    "Less than 45 minutes": false,
    "Less than 60 minutes": false,
    "More than 60 minutes": false,
    "Half a day": false,
    Variable: false,
  },
  Delivery: { "Face to Face": false, Virtual: false },
  Materials: {
    None: false,
    "Very little": false,
    Some: false,
    Lots: false,
  },
};

export default filterListInitial;
